# 1. External Secret para Postgres
{{- if .Values.postgres.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.postgres.vault.secretName }}-moodle
  labels:
    {{- include "moodle.labels" . | nindent 4 }}
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: "vault-backend-v2" # Assumindo nome fixo ou variável global
    kind: ClusterSecretStore
  target:
    name: {{ .Values.postgres.vault.secretName }}
    creationPolicy: Owner
  data:
    - secretKey: {{ .Values.postgres.vault.secretKey }} # Geralmente "password"
      remoteRef:
        key: {{ .Values.postgres.vault.path }}
        property: {{ .Values.postgres.vault.key }}
{{- end }}

---

# 2. External Secret para Redis/Valkey
{{- if .Values.redis.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.redis.vault.secretName }}-moodle
  labels:
    {{- include "moodle.labels" . | nindent 4 }}
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: "vault-backend-v2"
    kind: ClusterSecretStore
  target:
    name: {{ .Values.redis.vault.secretName }}
    creationPolicy: Owner
  data:
    - secretKey: {{ .Values.redis.vault.secretKey }} # Geralmente "redis-password"
      remoteRef:
        key: {{ .Values.redis.vault.path }}
        property: {{ .Values.redis.vault.key }}
{{- end }}
