#!/usr/bin/env bash
RED='\e[31m'
GREEN='\e[32m'
BLUE='\e[34m'
RESET='\e[0m'

set -e
if [ "$1" == "" ] || [ "$@" == "apache2-foreground" ]; then
    echo "Starting Moodle"
    cp /var/www/html/deploy/climaintenance.html /var/moodledata/climaintenance.html
    apache2ctl start

    php waitdb.php

    echo -e "${RED}Install Moodle database, if necessary.${RESET}" \
    && php admin/cli/install_database.php --agree-license --lang=en --adminuser=admin --adminpass=admin --adminemail=admin@server.local --fullname=Moodle --shortname=Moodle --summary=Moodle \
    && echo -e "${GREEN}Install Moodle: OK${RESET}"

    echo -e "${RED}Upgrade Moodle database, if necessary${RESET}" \
    && php admin/cli/upgrade.php --non-interactive --allow-unstable \
    && echo -e "${GREEN}Upgrade Moodle: OK"

    echo -e "${RED}Configura os padrões do IFRN${RESET}" \
    && php deploy/config_iniciais.php \
    && echo -e "${GREEN}Padrões do IFRN: OK${RESET}"

    echo -e "${RED}Baixa os content types do H5P${RESET}"
    php admin/cli/scheduled_task.php -f --execute=\\core\\task\\h5p_get_content_types_task >> /var/log/moodle/cron.log &
    echo -e "${GREEN}Upgrade Moodle: RODANDO EM BACKGROUND${RESET}"

    apache2ctl stop
    rm /var/moodledata/climaintenance.html
    /usr/local/bin/cron-loopexec.sh &
    sleep 5
fi

exec "$@"